name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # Add Node.js setup for JSII tests
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18' # Or a version compatible with your CDK version

    - name: Build with Maven
      run: mvn -B clean install --file pom.xml
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          tbot/target/surefire-reports/
          infra/target/surefire-reports/ 